# Generated by Django 3.2 on 2021-04-29 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_alter_employees_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'ordering': ('departmentName',)},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ('-dateOfJoin',)},
        ),
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeee', to='EmployeeApp.departments'),
        ),
    ]
